# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
TaxiHandle.create(city: "Addison", state: "TX", handle: "Addison-TX")
TaxiHandle.create(city: "Akron", state: "OH", handle: "Akron-OH")
TaxiHandle.create(city: "Alameda", state: "CA", handle: "Alameda-CA")
TaxiHandle.create(city: "Alamo", state: "CA", handle: "Alamo-CA")
TaxiHandle.create(city: "Albany", state: "CA", handle: "Albany-CA")
TaxiHandle.create(city: "Albany", state: "NY", handle: "Albany-NY")
TaxiHandle.create(city: "Albuquerque", state: "NM", handle: "Albuquerque-NM")
TaxiHandle.create(city: "Alexandria", state: "VA", handle: "Alexandria-VA")
TaxiHandle.create(city: "Allen", state: "TX", handle: "Allen-TX")
TaxiHandle.create(city: "Alpharetta", state: "GA", handle: "Alpharetta-GA")
TaxiHandle.create(city: "Amarillo", state: "TX", handle: "Amarillo-TX")
TaxiHandle.create(city: "American Canyon", state: "CA", handle: "American-Canyon-CA")
TaxiHandle.create(city: "Anaheim", state: "CA", handle: "Anaheim-CA")
TaxiHandle.create(city: "Anchorage", state: "AK", handle: "Anchorage-AK")
TaxiHandle.create(city: "Ann Arbor", state: "MI", handle: "Ann-Arbor-MI")
TaxiHandle.create(city: "Annapolis", state: "MD", handle: "Annapolis-MD")
TaxiHandle.create(city: "Arlington", state: "TX", handle: "Arlington-TX")
TaxiHandle.create(city: "Arlington", state: "VA", handle: "Arlington-VA")
TaxiHandle.create(city: "Ashville", state: "NC", handle: "Ashville-NC")
TaxiHandle.create(city: "Astoria", state: "OR", handle: "Astoria-OR")
TaxiHandle.create(city: "Athens", state: "GA", handle: "Athens-GA")
TaxiHandle.create(city: "Atlanta", state: "GA", handle: "Atlanta")
TaxiHandle.create(city: "Augusta", state: "GA", handle: "Augusta-GA")
TaxiHandle.create(city: "Aurora", state: "CO", handle: "Aurora-CO")
TaxiHandle.create(city: "Austin", state: "TX", handle: "Austin-TX")
TaxiHandle.create(city: "Bakersfield", state: "CA", handle: "Bakersfield-CA")
TaxiHandle.create(city: "Baltimore", state: "MD", handle: "Baltimore")
TaxiHandle.create(city: "Baton Rouge", state: "LA", handle: "Baton-Rouge-LA")
TaxiHandle.create(city: "Benicia", state: "CA", handle: "Benicia-CA")
TaxiHandle.create(city: "Berkeley", state: "CA", handle: "Berkeley-CA")
TaxiHandle.create(city: "Birmingham", state: "AL", handle: "Birmingham-AL")
TaxiHandle.create(city: "Bloomfield", state: "CT", handle: "Bloomfield-CT")
TaxiHandle.create(city: "Bloomington", state: "IL", handle: "Bloomington-IL")
TaxiHandle.create(city: "Bloomington", state: "MN", handle: "Bloomington-MN")
TaxiHandle.create(city: "Bluffton", state: "SC", handle: "Bluffton-SC")
TaxiHandle.create(city: "Boise", state: "ID", handle: "Boise-ID")
TaxiHandle.create(city: "Boston", state: "MA", handle: "Boston")
TaxiHandle.create(city: "Boulder", state: "CO", handle: "Boulder-CO")
TaxiHandle.create(city: "Bowie", state: "MD", handle: "Bowie-MD")
TaxiHandle.create(city: "Brentwood", state: "CA", handle: "Brentwood-CA")
TaxiHandle.create(city: "Bridgeport", state: "CT", handle: "Bridgeport-CT")
TaxiHandle.create(city: "Bridgeton", state: "NJ", handle: "Bridgeton-NJ")
TaxiHandle.create(city: "Bristol", state: "CT", handle: "Bristol-CT")
TaxiHandle.create(city: "Buda", state: "TX", handle: "Buda-TX")
TaxiHandle.create(city: "Buffalo", state: "NY", handle: "Buffalo")
TaxiHandle.create(city: "Burbank", state: "CA", handle: "Burbank-CA")
TaxiHandle.create(city: "Cambridge", state: "MA", handle: "Cambridge-MA")
TaxiHandle.create(city: "Campbell", state: "CA", handle: "Campbell-CA")
TaxiHandle.create(city: "Carlstadt", state: "NJ", handle: "Carlstadt-NJ")
TaxiHandle.create(city: "Carolina Beach", state: "NC", handle: "Carolina-Beach-NC")
TaxiHandle.create(city: "Castro Valley", state: "CA", handle: "Castro-Valley-CA")
TaxiHandle.create(city: "Cedar Rapids", state: "IA", handle: "Cedar-Rapids-IA")
TaxiHandle.create(city: "Champaign/Urbana", state: "IL", handle: "Champaign-Urbana-IL")
TaxiHandle.create(city: "Chandler", state: "AZ", handle: "Chandler-AZ")
TaxiHandle.create(city: "Chapel Hill", state: "NC", handle: "Chapel-Hill-NC")
TaxiHandle.create(city: "Charleston", state: "SC", handle: "Charleston-SC")
TaxiHandle.create(city: "Charlotte", state: "NC", handle: "Charlotte-NC")
TaxiHandle.create(city: "Charlottesville", state: "VA", handle: "Charlottesville-VA")
TaxiHandle.create(city: "Chattanooga", state: "TN", handle: "Chattanooga-TN")
TaxiHandle.create(city: "Chesapeake", state: "VA", handle: "Chesapeake-VA")
TaxiHandle.create(city: "Chicago", state: "IL", handle: "Chicago")
TaxiHandle.create(city: "Chula Vista", state: "CA", handle: "Chula-Vista-CA")
TaxiHandle.create(city: "Cincinnati", state: "OH", handle: "Cincinnati-OH")
TaxiHandle.create(city: "Clayton", state: "CA", handle: "Clayton-CA")
TaxiHandle.create(city: "Cleveland", state: "OH", handle: "Cleveland")
TaxiHandle.create(city: "Coachella Valley", state: "CA", handle: "Coachella-Valley-CA")
TaxiHandle.create(city: "College Park", state: "MD", handle: "College-Park-MD")
TaxiHandle.create(city: "Colorado Springs", state: "CO", handle: "Colorado-Springs-CO")
TaxiHandle.create(city: "Columbia", state: "SC", handle: "Columbia-SC")
TaxiHandle.create(city: "Columbus", state: "OH", handle: "Columbus-OH")
TaxiHandle.create(city: "Concord", state: "CA", handle: "Concord-CA")
TaxiHandle.create(city: "Cooperstown", state: "NY", handle: "Cooperstown-NY")
TaxiHandle.create(city: "Corpus Christi", state: "TX", handle: "Corpus-Christi-TX")
TaxiHandle.create(city: "Costa Mesa", state: "CA", handle: "Costa-Mesa-CA")
TaxiHandle.create(city: "Crofton", state: "MD", handle: "Crofton-MD")
TaxiHandle.create(city: "Cupertino", state: "CA", handle: "Cupertino-CA")
TaxiHandle.create(city: "Dallas", state: "TX", handle: "Dallas")
TaxiHandle.create(city: "Danbury", state: "CT", handle: "Danbury-CT")
TaxiHandle.create(city: "Danville", state: "CA", handle: "Danville-CA")
TaxiHandle.create(city: "Davis", state: "CA", handle: "Davis-CA")
TaxiHandle.create(city: "Daytona Beach", state: "FL", handle: "Daytona-Beach-FL")
TaxiHandle.create(city: "Denver", state: "CO", handle: "Denver")
TaxiHandle.create(city: "Des Moines", state: "IA", handle: "Des-Moines-IA")
TaxiHandle.create(city: "Detroit", state: "MI", handle: "Detroit")
TaxiHandle.create(city: "District Heights", state: "MD", handle: "District-Heights-MD")
TaxiHandle.create(city: "Dover", state: "DE", handle: "Dover-DE")
TaxiHandle.create(city: "Downey", state: "CA", handle: "Downey-CA")
TaxiHandle.create(city: "Dublin", state: "CA", handle: "Dublin-CA")
TaxiHandle.create(city: "Dulles", state: "VA", handle: "Dulles-VA")
TaxiHandle.create(city: "Duluth", state: "GA", handle: "Duluth-GA")
TaxiHandle.create(city: "Duluth", state: "MN", handle: "Duluth-MN")
TaxiHandle.create(city: "Dunwoody", state: "GA", handle: "Dunwoody-GA")
TaxiHandle.create(city: "Durham", state: "NC", handle: "Durham-NC")
TaxiHandle.create(city: "East Rutherford", state: "NJ", handle: "East-Rutherford-NJ")
TaxiHandle.create(city: "Edgewater", state: "FL", handle: "Edgewater-FL")
TaxiHandle.create(city: "El Cerrito", state: "CA", handle: "El-Cerrito-CA")
TaxiHandle.create(city: "El Monte", state: "CA", handle: "El-Monte-CA")
TaxiHandle.create(city: "El Paso", state: "TX", handle: "El-Paso-TX")
TaxiHandle.create(city: "Emerald Isle", state: "NC", handle: "Emerald-Isle-NC")
TaxiHandle.create(city: "Emeryville", state: "CA", handle: "Emeryville-CA")
TaxiHandle.create(city: "Encinitas", state: "CA", handle: "Encinitas-CA")
TaxiHandle.create(city: "Erie", state: "PA", handle: "Erie-PA")
TaxiHandle.create(city: "Escondido", state: "CA", handle: "Escondido-CA")
TaxiHandle.create(city: "Eugene", state: "OR", handle: "Eugene-OR")
TaxiHandle.create(city: "Fairfax", state: "VA", handle: "Fairfax-VA")
TaxiHandle.create(city: "Fairfield", state: "CA", handle: "Fairfield-CA")
TaxiHandle.create(city: "Falls Church", state: "VA", handle: "Falls-Church-VA")
TaxiHandle.create(city: "Fargo", state: "ND", handle: "Fargo-ND")
TaxiHandle.create(city: "Farmington", state: "CT", handle: "Farmington-CT")
TaxiHandle.create(city: "Folly Beach", state: "SC", handle: "Folly-Beach-SC")
TaxiHandle.create(city: "Fontana", state: "CA", handle: "Fontana-CA")
TaxiHandle.create(city: "Fort Collins", state: "CO", handle: "Fort-Collins-CO")
TaxiHandle.create(city: "Fort Lauderdale", state: "FL", handle: "Fort-Lauderdale-FL")
TaxiHandle.create(city: "Fort Meade", state: "MD", handle: "Fort-Meade-MD")
TaxiHandle.create(city: "Fort Wayne", state: "IN", handle: "Fort-Wayne-IN")
TaxiHandle.create(city: "Fort Worth", state: "TX", handle: "Fort-Worth-TX")
TaxiHandle.create(city: "Framingham", state: "MA", handle: "Framingham-MA")
TaxiHandle.create(city: "Fremont", state: "CA", handle: "Fremont-CA")
TaxiHandle.create(city: "Fresno", state: "CA", handle: "Fresno-CA")
TaxiHandle.create(city: "Frisco", state: "TX", handle: "Frisco-TX")
TaxiHandle.create(city: "Fullerton", state: "CA", handle: "Fullerton-CA")
TaxiHandle.create(city: "Gainesville", state: "FL", handle: "Gainesville-FL")
TaxiHandle.create(city: "Garden Grove", state: "CA", handle: "Garden-Grove-CA")
TaxiHandle.create(city: "Garland", state: "TX", handle: "Garland-TX")
TaxiHandle.create(city: "Gilbert", state: "AZ", handle: "Gilbert-AZ")
TaxiHandle.create(city: "Glenarden", state: "MD", handle: "Glenarden-MD")
TaxiHandle.create(city: "Glendale", state: "AZ", handle: "Glendale-AZ")
TaxiHandle.create(city: "Glendale", state: "CA", handle: "Glendale-CA")
TaxiHandle.create(city: "Gloucester", state: "MA", handle: "Gloucester-MA")
TaxiHandle.create(city: "Grand Rapids", state: "MI", handle: "Grand-Rapids-MI")
TaxiHandle.create(city: "Grapevine", state: "TX", handle: "Grapevine-TX")
TaxiHandle.create(city: "Greenbelt", state: "MD", handle: "Greenbelt-MD")
TaxiHandle.create(city: "Greensboro", state: "NC", handle: "Greensboro-NC")
TaxiHandle.create(city: "Greenville", state: "SC", handle: "Greenville-SC")
TaxiHandle.create(city: "Greenwich", state: "CT", handle: "Greenwich-CT")
TaxiHandle.create(city: "Guerneville", state: "CA", handle: "Guerneville-CA")
TaxiHandle.create(city: "Hackensack", state: "NJ", handle: "Hackensack-NJ")
TaxiHandle.create(city: "Hampton", state: "VA", handle: "Hampton-VA")
TaxiHandle.create(city: "Hamptons", state: "NY", handle: "Hamptons-NY")
TaxiHandle.create(city: "Harrisburg", state: "PA", handle: "Harrisburg-PA")
TaxiHandle.create(city: "Hartford", state: "CT", handle: "Hartford-CT")
TaxiHandle.create(city: "Hasbrouck Heights", state: "NJ", handle: "Hasbrouck-Heights-NJ")
TaxiHandle.create(city: "Hayward", state: "CA", handle: "Hayward-CA")
TaxiHandle.create(city: "Henderson", state: "NV", handle: "Henderson-NV")
TaxiHandle.create(city: "Hilton Head Island", state: "SC", handle: "Hilton-Head-Island-SC")
TaxiHandle.create(city: "Honolulu", state: "HI", handle: "Honolulu")
TaxiHandle.create(city: "Houston", state: "TX", handle: "Houston")
TaxiHandle.create(city: "Huntington Beach", state: "CA", handle: "Huntington-Beach-CA")
TaxiHandle.create(city: "Huntsville", state: "AL", handle: "Huntsville-AL")
TaxiHandle.create(city: "Hyattsville", state: "MD", handle: "Hyattsville-MD")
TaxiHandle.create(city: "Indianapolis", state: "IN", handle: "Indianapolis-IN")
TaxiHandle.create(city: "Inglewood", state: "CA", handle: "Inglewood-CA")
TaxiHandle.create(city: "Inland Empire", state: "CA", handle: "Inland-Empire-CA")
TaxiHandle.create(city: "Iowa City", state: "IA", handle: "Iowa-City-IA")
TaxiHandle.create(city: "Irvine", state: "CA", handle: "Irvine-CA")
TaxiHandle.create(city: "Irving", state: "TX", handle: "Irving-TX")
TaxiHandle.create(city: "Isle of Palms", state: "SC", handle: "Isle-of-Palms-SC")
TaxiHandle.create(city: "Jackson", state: "MS", handle: "Jackson-MS")
TaxiHandle.create(city: "Jacksonville", state: "FL", handle: "Jacksonville-FL")
TaxiHandle.create(city: "Jamestown", state: "RI", handle: "Jamestown-RI")
TaxiHandle.create(city: "Jersey City", state: "NJ", handle: "Jersey-City-NJ")
TaxiHandle.create(city: "Johns Creek", state: "GA", handle: "Johns-Creek-GA")
TaxiHandle.create(city: "Kansas City", state: "MO", handle: "KC")
TaxiHandle.create(city: "Kauai", state: "HI", handle: "Kauai-HI")
TaxiHandle.create(city: "Keller", state: "TX", handle: "Keller-TX")
TaxiHandle.create(city: "Kiawah Island", state: "SC", handle: "Kiawah-Island-SC")
TaxiHandle.create(city: "Knoxville", state: "TN", handle: "Knoxville-TN")
TaxiHandle.create(city: "Kyle", state: "TX", handle: "Kyle-TX")
TaxiHandle.create(city: "Lafayette", state: "CA", handle: "Lafayette-CA")
TaxiHandle.create(city: "Lancaster", state: "CA", handle: "Lancaster-CA")
TaxiHandle.create(city: "Lansing", state: "MI", handle: "Lansing-MI")
TaxiHandle.create(city: "Laredo", state: "TX", handle: "Laredo-TX")
TaxiHandle.create(city: "Las Vegas", state: "NV", handle: "LV")
TaxiHandle.create(city: "Laurel", state: "MD", handle: "Laurel-MD")
TaxiHandle.create(city: "Lawrence", state: "KS", handle: "Lawrence-KS")
TaxiHandle.create(city: "Leominster", state: "MA", handle: "Leominster-MA")
TaxiHandle.create(city: "Lewisburg", state: "PA", handle: "Lewisburg-PA")
TaxiHandle.create(city: "Lexington", state: "KY", handle: "Lexington-KY")
TaxiHandle.create(city: "Lincoln", state: "NE", handle: "Lincoln-NE")
TaxiHandle.create(city: "Little Five Points", state: "GA", handle: "Little-Five-Points-GA")
TaxiHandle.create(city: "Livermore", state: "CA", handle: "Livermore-CA")
TaxiHandle.create(city: "Long Beach", state: "CA", handle: "Long-Beach-CA")
TaxiHandle.create(city: "Los Angeles", state: "CA", handle: "LA")
TaxiHandle.create(city: "Los Gatos", state: "CA", handle: "Los-Gatos-CA")
TaxiHandle.create(city: "Louisville", state: "KY", handle: "Louisville-KY")
TaxiHandle.create(city: "Lowell", state: "MA", handle: "Lowell-MA")
TaxiHandle.create(city: "Lubbock", state: "TX", handle: "Lubbock-TX")
TaxiHandle.create(city: "Lyndhurst", state: "NJ", handle: "Lyndhurst-NJ")
TaxiHandle.create(city: "Madison", state: "CT", handle: "Madison-CT")
TaxiHandle.create(city: "Madison", state: "WI", handle: "Madison-WI")
TaxiHandle.create(city: "Manassas", state: "VA", handle: "Manassas-VA")
TaxiHandle.create(city: "Manistee", state: "MI", handle: "Manistee-MI")
TaxiHandle.create(city: "Mansfield", state: "PA", handle: "Mansfield-PA")
TaxiHandle.create(city: "Martinez", state: "CA", handle: "Martinez-CA")
TaxiHandle.create(city: "Maui", state: "HI", handle: "Maui-HI")
TaxiHandle.create(city: "McKinney", state: "TX", handle: "McKinney-TX")
TaxiHandle.create(city: "McLean", state: "VA", handle: "McLead-VA")
TaxiHandle.create(city: "Memphis", state: "TN", handle: "Memphis-TN")
TaxiHandle.create(city: "Mesa", state: "AZ", handle: "Mesa-AZ")
TaxiHandle.create(city: "Miami", state: "FL", handle: "Miami")
TaxiHandle.create(city: "Milpitas", state: "CA", handle: "Milpitas-CA")
TaxiHandle.create(city: "Milwaukee", state: "WI", handle: "Milwaukee")
TaxiHandle.create(city: "Minneapolis", state: "MN", handle: "Minneapolis")
TaxiHandle.create(city: "Mocksville", state: "NC", handle: "Mocksville-NC")
TaxiHandle.create(city: "Modesto", state: "CA", handle: "Modesto-CA")
TaxiHandle.create(city: "Monterey", state: "CA", handle: "Monterey-CA")
TaxiHandle.create(city: "Montgomery", state: "AL", handle: "Montgomery-AL")
TaxiHandle.create(city: "Mount Rainier", state: "MD", handle: "Mount-Rainier-MD")
TaxiHandle.create(city: "Mountain View", state: "CA", handle: "Mountain-View-CA")
TaxiHandle.create(city: "Myrtle Beach", state: "SC", handle: "Myrtle-Beach-SC")
TaxiHandle.create(city: "Mystic", state: "CT", handle: "Mystic-CT")
TaxiHandle.create(city: "Napa Valley", state: "CA", handle: "Napa-Valley-CA")
TaxiHandle.create(city: "Napa", state: "CA", handle: "Napa-CA")
TaxiHandle.create(city: "Naples", state: "FL", handle: "Naples-FL")
TaxiHandle.create(city: "Narragansett", state: "RI", handle: "Narragansett-RI")
TaxiHandle.create(city: "Nashville", state: "TN", handle: "Nashville-TN")
TaxiHandle.create(city: "Natick", state: "MA", handle: "Natick-MA")
TaxiHandle.create(city: "New Carrollton", state: "MD", handle: "New-Carrollton-MD")
TaxiHandle.create(city: "New Haven", state: "CT", handle: "New-Haven-CT")
TaxiHandle.create(city: "New Jersey Shore", state: "NJ", handle: "New-Jersey-Shore-NJ")
TaxiHandle.create(city: "New London", state: "CT", handle: "New-London-CT")
TaxiHandle.create(city: "New Orleans", state: "LA", handle: "New-Orleans-LA")
TaxiHandle.create(city: "New Smyrna Beach", state: "FL", handle: "New-Smyrna-Beach-FL")
TaxiHandle.create(city: "New York", state: "NY", handle: "NY")
TaxiHandle.create(city: "Newark", state: "NJ", handle: "Newark-NJ")
TaxiHandle.create(city: "Newport News", state: "VA", handle: "Newport-News-VA")
TaxiHandle.create(city: "Newport", state: "RI", handle: "Newport-RI")
TaxiHandle.create(city: "Newton", state: "MA", handle: "Newton-MA")
TaxiHandle.create(city: "Norcross", state: "GA", handle: "Norcross-GA")
TaxiHandle.create(city: "Norfolk", state: "VA", handle: "Norfolk-VA")
TaxiHandle.create(city: "Norman", state: "OK", handle: "Norman-OK")
TaxiHandle.create(city: "North Arlington", state: "NJ", handle: "North-Arlington-NJ")
TaxiHandle.create(city: "Norwalk", state: "CA", handle: "Norwalk-CA")
TaxiHandle.create(city: "Norwalk", state: "CT", handle: "Norwalk-CT")
TaxiHandle.create(city: "Nutley", state: "NJ", handle: "Nutley-NJ")
TaxiHandle.create(city: "Oakland", state: "CA", handle: "Oakland-CA")
TaxiHandle.create(city: "Ocean City", state: "MD", handle: "Ocean-City-MD")
TaxiHandle.create(city: "Odenton", state: "MD", handle: "Odenton-MD")
TaxiHandle.create(city: "Oklahoma City", state: "OK", handle: "Oklahoma-City-OK")
TaxiHandle.create(city: "Omaha / Council Bluffs", state: "NE", handle: "Omaha-NE")
TaxiHandle.create(city: "Oneonta ", state: "NY", handle: "Oneonta-NY")
TaxiHandle.create(city: "Ontario", state: "CA", handle: "Ontario-CA")
TaxiHandle.create(city: "Orange County", state: "CA", handle: "Orange-County-CA")
TaxiHandle.create(city: "Orlando", state: "FL", handle: "Orlando")
TaxiHandle.create(city: "Ormond Beach", state: "FL", handle: "Ormond-Beach-FL")
TaxiHandle.create(city: "Palm Beach", state: "FL", handle: "Palm-Beach-FL")
TaxiHandle.create(city: "Palm Desert", state: "CA", handle: "Palm-Desert-CA")
TaxiHandle.create(city: "Palm Springs", state: "CA", handle: "Palm-Springs-CA")
TaxiHandle.create(city: "Palmdale", state: "CA", handle: "Palmdale-CA")
TaxiHandle.create(city: "Palo Alto", state: "CA", handle: "Palo-Alto-CA")
TaxiHandle.create(city: "Pasadena", state: "CA", handle: "Pasadena-CA")
TaxiHandle.create(city: "Paterson", state: "NJ", handle: "Paterson-NJ")
TaxiHandle.create(city: "Peachtree Corners", state: "GA", handle: "Peachtree-Corners-GA")
TaxiHandle.create(city: "Pensacola", state: "FL", handle: "Pensacola-FL")
TaxiHandle.create(city: "Peoria", state: "AZ", handle: "Peoria-AZ")
TaxiHandle.create(city: "Philadelphia", state: "PA", handle: "Philadelphia")
TaxiHandle.create(city: "Phoenix", state: "AZ", handle: "Phoenix")
TaxiHandle.create(city: "Piedmont", state: "CA", handle: "Piedmont-CA")
TaxiHandle.create(city: "Pittsburgh", state: "PA", handle: "Pittsburgh")
TaxiHandle.create(city: "Placerville", state: "CA", handle: "Placerville-CA")
TaxiHandle.create(city: "Plano", state: "TX", handle: "Plano-TX")
TaxiHandle.create(city: "Pleasant Hill", state: "CA", handle: "Pleasant-Hill-CA")
TaxiHandle.create(city: "Pleasanton", state: "CA", handle: "Pleasanton-CA")
TaxiHandle.create(city: "Pomona", state: "CA", handle: "Pomona-CA")
TaxiHandle.create(city: "Pooler", state: "GA", handle: "Pooler-GA")
TaxiHandle.create(city: "Portage", state: "IN", handle: "Portage-IN")
TaxiHandle.create(city: "Portland", state: "ME", handle: "Portland-ME")
TaxiHandle.create(city: "Portland", state: "OR", handle: "Portland")
TaxiHandle.create(city: "Prince George's County", state: "MD", handle: "Prince-Georges-County")
TaxiHandle.create(city: "Princeton", state: "NJ", handle: "Princeton-NJ")
TaxiHandle.create(city: "Providence", state: "RI", handle: "Providence-RI")
TaxiHandle.create(city: "Raleigh", state: "NC", handle: "Raleigh-NC")
TaxiHandle.create(city: "Rancho Cordova", state: "CA", handle: "Rancho-Cordova")
TaxiHandle.create(city: "Rancho Cucamonga", state: "CA", handle: "Rancho-Cucamonga-CA")
TaxiHandle.create(city: "Reston", state: "VA", handle: "Reston-VA")
TaxiHandle.create(city: "Revere", state: "MA", handle: "Revere-MA")
TaxiHandle.create(city: "Richardson", state: "TX", handle: "Richardson-TX")
TaxiHandle.create(city: "Richmond Hill", state: "GA", handle: "Richmond-Hill-GA")
TaxiHandle.create(city: "Richmond", state: "CA", handle: "Richmond-CA")
TaxiHandle.create(city: "Richmond", state: "VA", handle: "Richmond-VA")
TaxiHandle.create(city: "Rincon", state: "GA", handle: "Rincon-GA")
TaxiHandle.create(city: "Riverside", state: "CA", handle: "Riverside-CA")
TaxiHandle.create(city: "Roanoke", state: "VA", handle: "Roanoke-VA")
TaxiHandle.create(city: "Rochester", state: "NY", handle: "Rochester-NY")
TaxiHandle.create(city: "Roswell", state: "GA", handle: "Roswell-GA")
TaxiHandle.create(city: "Rutherford", state: "NJ", handle: "Rutherford-NJ")
TaxiHandle.create(city: "Sacramento", state: "CA", handle: "Sacramento-CA")
TaxiHandle.create(city: "Salt Lake City", state: "UT", handle: "SLC")
TaxiHandle.create(city: "San Antonio", state: "TX", handle: "San-Antonio-TX")
TaxiHandle.create(city: "San Bernardino", state: "CA", handle: "San-Bernardino-CA")
TaxiHandle.create(city: "San Diego", state: "CA", handle: "SD")
TaxiHandle.create(city: "San Francisco", state: "CA", handle: "SF")
TaxiHandle.create(city: "San Jose", state: "CA", handle: "San-Jose-CA")
TaxiHandle.create(city: "San Leandro", state: "CA", handle: "San-Leandro-CA")
TaxiHandle.create(city: "San Lorenzo", state: "CA", handle: "San-Lorenzo-CA")
TaxiHandle.create(city: "San Marcos", state: "TX", handle: "San-Marcos-TX")
TaxiHandle.create(city: "San Mateo", state: "CA", handle: "San-Mateo-CA")
TaxiHandle.create(city: "San Ramon", state: "CA", handle: "San-Ramon-CA")
TaxiHandle.create(city: "Santa Ana", state: "CA", handle: "Santa-Ana-CA")
TaxiHandle.create(city: "Santa Barbara", state: "CA", handle: "Santa-Barbara-CA")
TaxiHandle.create(city: "Santa Clara", state: "CA", handle: "Santa-Clara-CA")
TaxiHandle.create(city: "Santa Clarita", state: "CA", handle: "Santa-Clarita-CA")
TaxiHandle.create(city: "Santa Rosa", state: "CA", handle: "Santa-Rosa-CA")
TaxiHandle.create(city: "Saratoga", state: "CA", handle: "Saratoga-CA")
TaxiHandle.create(city: "Savannah", state: "GA", handle: "Savannah-GA")
TaxiHandle.create(city: "Scottsdale", state: "AZ", handle: "Scottsdale-AZ")
TaxiHandle.create(city: "Seat Pleasant", state: "MD", handle: "Seat-Pleasant-MD")
TaxiHandle.create(city: "Seattle", state: "WA", handle: "Seattle")
TaxiHandle.create(city: "Severna Park", state: "MD", handle: "Severna-Park-MD")
TaxiHandle.create(city: "Silicon Valley", state: "CA", handle: "Silicon-Valley-CA")
TaxiHandle.create(city: "Simi Valley", state: "CA", handle: "Simi-Valley-CA")
TaxiHandle.create(city: "Sonoma Valley", state: "CA", handle: "Sonoma-Valley-CA")
TaxiHandle.create(city: "Spokane", state: "WA", handle: "Spokane-WA")
TaxiHandle.create(city: "Springfield ", state: "OH", handle: "Springfield-OH")
TaxiHandle.create(city: "Springfield", state: "MO", handle: "Springfield-MO")
TaxiHandle.create(city: "St. Augustine", state: "FL", handle: "St-Augustine-FL")
TaxiHandle.create(city: "St. Louis", state: "MO", handle: "SL")
TaxiHandle.create(city: "St. Michaels", state: "MD", handle: "St-Michaels-MD")
TaxiHandle.create(city: "St. Paul", state: "MN", handle: "St.-Paul-MN")
TaxiHandle.create(city: "St. Petersburg", state: "FL", handle: "St.-Petersburg-FL")
TaxiHandle.create(city: "Stamford", state: "CT", handle: "Stamford-CT")
TaxiHandle.create(city: "Stanford", state: "CA", handle: "Stanford-CA")
TaxiHandle.create(city: "State College", state: "PA", handle: "State-College-PA")
TaxiHandle.create(city: "Sterling", state: "VA", handle: "Sterling-VA")
TaxiHandle.create(city: "Stockton", state: "CA", handle: "Stockton-CA")
TaxiHandle.create(city: "Suisun", state: "CA", handle: "Suisun-CA")
TaxiHandle.create(city: "Sunnyvale", state: "CA", handle: "Sunnyvale-CA")
TaxiHandle.create(city: "Sunol", state: "CA", handle: "Sunol-CA")
TaxiHandle.create(city: "Surprise", state: "AZ", handle: "Surprise-AZ")
TaxiHandle.create(city: "Suwanee", state: "GA", handle: "Suwanee-GA")
TaxiHandle.create(city: "Syracuse", state: "NY", handle: "Syracuse-NY")
TaxiHandle.create(city: "Tacoma", state: "WA", handle: "Tacoma-WA")
TaxiHandle.create(city: "Tallahassee", state: "FL", handle: "Tallahassee-FL")
TaxiHandle.create(city: "Tampa", state: "FL", handle: "Tampa-FL")
TaxiHandle.create(city: "Tempe", state: "AZ", handle: "Tempe-AZ")
TaxiHandle.create(city: "Toledo", state: "OH", handle: "Toledo-OH")
TaxiHandle.create(city: "Topeka", state: "KS", handle: "Topeka-KS")
TaxiHandle.create(city: "Torrance", state: "CA", handle: "Torrance-CA")
TaxiHandle.create(city: "Trenton", state: "NJ", handle: "Trenton-NJ")
TaxiHandle.create(city: "Troy", state: "NY", handle: "Troy-NY")
TaxiHandle.create(city: "Tucson", state: "AZ", handle: "Tucson-AZ")
TaxiHandle.create(city: "Tulsa", state: "OK", handle: "Tulsa-OK")
TaxiHandle.create(city: "Tysons Corner", state: "VA", handle: "Tysons-Corner-VA")
TaxiHandle.create(city: "Union City", state: "CA", handle: "Union-City-CA")
TaxiHandle.create(city: "Vallejo", state: "CA", handle: "Vallejo-CA")
TaxiHandle.create(city: "Vienna", state: "VA", handle: "Vienna-VA")
TaxiHandle.create(city: "Virginia Beach", state: "VA", handle: "Virginia-Beach-VA")
TaxiHandle.create(city: "Walnut Creek", state: "CA", handle: "Walnut-Creek-CA")
TaxiHandle.create(city: "Waltham", state: "MA", handle: "Waltham-MA")
TaxiHandle.create(city: "Washington", state: "DC", handle: "Washington-DC")
TaxiHandle.create(city: "Wellsboro", state: "PA", handle: "Wellsboro-PA")
TaxiHandle.create(city: "West Covina", state: "CA", handle: "West-Covina-CA")
TaxiHandle.create(city: "Wichita", state: "KS", handle: "Wichita-KS")
TaxiHandle.create(city: "Wilmington", state: "DE", handle: "Wilmington-DE")
TaxiHandle.create(city: "Wilmington", state: "NC", handle: "Wilmington-NC")
TaxiHandle.create(city: "Winchester", state: "VA", handle: "Winchester-VA")
TaxiHandle.create(city: "Windsor", state: "CT", handle: "Windsor-CT")
TaxiHandle.create(city: "Winston-Salem", state: "NC", handle: "Winston-Salem-NC")
TaxiHandle.create(city: "Woodbridge", state: "VA", handle: "Woodbridge-VA")
TaxiHandle.create(city: "Woodbury", state: "MN", handle: "Woodbury-MN")
TaxiHandle.create(city: "Worcester", state: "MA", handle: "Worcester-MA")
TaxiHandle.create(city: "Wrightsville Beach", state: "NC", handle: "Wrightsville-Beach-NC")
TaxiHandle.create(city: "Yorktown", state: "VA", handle: "Yorktown-VA")
TaxiHandle.create(city: "Yountville", state: "CA", handle: "Yountville-CA")
